# Custom Language File for Launcher Customizer

[ejs.app]
title = "Baking Soda Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/7EAWGPR9Ge"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "Baking Soda"
welcomeDescription = "Baking Soda is a performance-oriented mod-pack for SakuraFalls, a Minecraft Server. We hope you enjoy it!"
welcomeDescCTA = ""
