# Custom Language File for Launcher Customizer

[ejs.app]
title = "Baking Soda Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/dscalzi/HeliosLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/7EAWGPR9Ge"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "SakuraFalls"
welcomeDescription = "SakuraFalls is a Minecraft Roleplay Server set in a modern city, done right."
welcomeDescCTA = ""
