# Custom Language File for Launcher Customizer

[ejs.app]
title = "Baking Soda Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/fishydarwin/BakingSodaLauncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/7EAWGPR9Ge"

[ejs.settings]
sourceGithubLink = "https://github.com/fishydarwin/BakingSodaLauncher"
supportLink = "https://github.com/fishydarwin/BakingSodaLauncher/issues"

[ejs.welcome]
welcomeHeader = "Baking Soda"
welcomeDescription = "Baking Soda is a performance-oriented mod-pack for SakuraFalls, a Minecraft Server."
welcomeDescCTA = "Baking Soda Launcher is based on HeliosLauncher. We hope you enjoy it!"
